language: java
if: tag IS present OR NOT (branch == master)
# before_cache:
#   - export MAVEN_LOCAL_REPOSITORY=$(mvn -B help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
# cache:
#   directories:
#     - $MAVEN_LOCAL_REPOSITORY
install: mvn -q dependency:resolve
jdk:
  - openjdk8
before_script:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] || [ "${TRAVIS_TAG}X" != "X" ]; then
      mvn -q versions:set@remove-snapshot versions:commit@remove-snapshot -B;
    fi
script:
  - |
    mvn clean package -B
    if [ "$TRAVIS_BRANCH" = "master" ] || [ "${TRAVIS_TAG}X" != "X" ]; then
      ## Only run these commands when building a release
      mvn sonar:sonar -Dsonar.login=${SONAR_PROJECT_TOKEN} -B
      mvn -q dependency-check:check -B
      mvn -q bundle:bundle -B
    fi
before_deploy:
  - export BUNDLE_JAR=$(ls nexus*jar)
  - echo "deploying $BUNDLE_JAR to GitHub releases"
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file:
    - "${BUNDLE_JAR}"
    - "target/site/jacoco/*"
    - "target/dependency-check-report.html"
  skip_cleanup: true
  on:
    tags: true
after_success:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] || [ "${TRAVIS_TAG}X" != "X" ]; then
      mvn -q versions:set@rev-to-next-snapshot versions:commit@rev-to-next-snapshot -B
      git config --global user.name "Travis CI"
      git config --global user.email "travis@travisci.org"
      git checkout -b version-branch
      git commit pom.xml -m 'Bumped micro version'
      git checkout ${TRAVIS_BRANCH}
      git merge version-branch -s theirs
      git remote add pushorigin https://${GITHUB_OAUTH_TOKEN}@github.com/InfoSec812/nexus-kubernetes-openshift.git
      git push pushorigin master
    fi
    if [ "$TRAVIS_BRANCH" = "Fix-after-success-stage" ] || [ "${TRAVIS_TAG}X" != "X" ]; then
      mvn -q versions:set@rev-to-next-snapshot versions:commit@rev-to-next-snapshot -B
      git config --global user.name "Travis CI"
      git config --global user.email "travis@travisci.org"
      git fetch --all
      git checkout -b version-branch
      git commit pom.xml -m 'Bumped micro version'
      git checkout ${TRAVIS_BRANCH}
      git merge version-branch -s theirs
      git remote add pushorigin https://${GITHUB_OAUTH_TOKEN}@github.com/InfoSec812/nexus-kubernetes-openshift.git
      git push pushorigin Fix-after-success-stage
    fi